### ISSUE TITLE
Tracking parsing progress

### ISSUE THREAD

**Issue by ceranco** [adwhit/itchy-rust#19]
Hi, I'm interested in tracking the parsing progress of `MessageStream`, especially so I can log some progress indicators.   
Exposing `MessageStream.bytes_read`  will be enough for that:

```rust
while let Some(message) = stream.next() {
  let message = message.unwrap();
  // ...
  println!("Num bytes read: {}", stream.get_bytes_read());
}
```

Additionally, adding specific `get_size` impls for `MessageStream<File>` and `MessageStream<GzDecoder<File>>`  would allow tracking percentages easily without having to create the readers outside of `MessageStream`.

Would you be open to accepting a PR that implements these behaviors?

**Comment by adwhit** [comment]
Hi - sure, I'd accept a PR, as long as it is not too invasive

**Comment by ceranco** [comment]
Thanks! I opened the pr: #20
